# On Linux/BSD
# import = [
#     "~/.config/alacritty/themes/github_light_default.toml",
# ]
# On Windows
import = [
    "C:\\Users\\chenc\\AppData\\Roaming\\alacritty\\themes\\github_light_default.toml",
]

[shell]
program = "wsl.exe"
args = ["--distribution", "Ubuntu-22.04"]

[window]
dynamic_padding = true
opacity = 0.9
startup_mode = "Maximized"

[scrolling]
history = 100000

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 12
offset = { x = 1, y = 1 }
glyph_offset = { x = 0, y = 1 }

[selection]
save_to_clipboard = true

[[hints.enabled]]
# On Linux/BSD
# command = "xdg-open"
# On macOS
# command = "open" 
# On Windows
command = { program = "cmd", args = ["/c", "start", ""] }
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "W", mods = "Control|Shift", action = "Quit" },
]
